#################### default parameters ################################
# favicon
favicon = "https://cdn.discordapp.com/attachments/1148600287989342268/1149625913714159686/vjery-media-logo-transparant.png"
# logo
logo = "https://cdn.discordapp.com/attachments/1148600287989342268/1149625913714159686/vjery-media-logo-transparant.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "200x"
# logo text will only show when logo is missing.
logo_text = "Vjery Media"
# navbar fixed to top
navbar_fixed = true
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "https://cdn.discordapp.com/attachments/1148600287989342268/1149625913714159686/vjery-media-logo-transparant.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "Tilburg, The Netherlands"
mobile = "(0)85 000 00 000"
email = "info@vjey.org"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true

# Posts related Titles & Contents
categories_title = "Blog Categories"
posts_title = "Featured"
featured_post_title = "Aanbevolen Artikelen"
recent_post_title = "Meest Recente Artikelen"
featured_post_button = "Aanbevolen"
recent_post_button = "Recent"
read_more_button = "Lees meer"
previous_button = "Terug"
next_button = "Volgende"
related_posts = "Gerelateerde Artikelen"
showing_posts = "Gereleteerde Artikelen Van"
no_categories_found = "Geen Categorie Gevonden"
no_tags_found = "Geen Tag Gevonden"

mainSections = ["blog"]
# about widget content
about_widget_content = "Lorem ipsum dolor sit amet, conse tfctetur adipiscing elit. Vel in in donec iaculis tempasus odio nunc laoreet . Libero ullam rgscorper."
# footer content
footer_content = "Vjery Media. De platform voor het laaste nieuws, sport nieuws of leuke weetjes!"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""
# copyright
theme_copyright = true
copyright = "©️ Copyrighted by Vjery Media - 2023"

# 404
error_404_text = "404 Pagina niet gevonden!"
error_404_button = "Breng me terug"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Vjery **Media**"
title_small = "Bekijk het laaste nieuws"
image = "images/banner.png"
background_image = "/images/banner-bg-shape.svg"
content = "Lees hier de laaste nieuwtjes, leuke weetjes en het actuele sport uitlagen."
button_label = "Know About Us"
button_link = "about/"

# Advertise
[advertisement]
image = "images/promotion.png"
link = "mailto:colab@vjery.org"

# cookies
[cookies]
enable = false
expire_days = 2
content = "Onze website maakt gebruik van cookies. 🍪 Bij het gebruik maken van deze website ga je hiermee automatisch akkoord."
button = "Accepteren"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
newsletter_title = "Nieuwsbrief"
newsletter_invitation = "Neem deel, net zoals duizend andere mensen, aan onze mailing groep!"
newsletter_placeholder = "Typ ier en klik op aanmelden"
newsletter_reminder_a = "Bij het aanmelden, Ga je akkoord met de"
newsletter_reminder_b = "Privacy Policy"
newsletter_button = "Aanmelden"
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"
